#server
server:
  port: 80
  contextPath: /${mainArtifactId}-${artifactId}

spring:
  jackson:
    serialization:
      indent_output: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false

dept:
  service:
    baseUrl: http://${mainArtifactId}.service.zengrd.com/${mainArtifactId}-service