#server
server:
  port: 80
  contextPath: /${mainArtifactId}-${artifactId}

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zengrd.com:3306/${mainArtifactId}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: ${mainArtifactId}
    password: ${mainArtifactId}1213
    test-on-boorow: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      indent_output: true