package ${package}.pojo.domain;

import java.io.Serializable;

public class Demo implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -388849793135578953L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.status
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.status
     *
     * @return the value of demo.status
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.status
     *
     * @param status the value for demo.status
     *
     * @mbg.generated Sun Feb 25 15:50:06 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}